PackageIdentifier: Yubico.Authenticator
PackageVersion: 5.0.5
PackageName: Yubico Authenticator
Moniker: yubioath
Tags:
- 2fa
- security
- auth
- totp
ShortDescription: Authenticator to generate 2-step verification codes using your YubiKey
PackageUrl: https://www.yubico.com/products/yubico-authenticator/
Publisher: Yubico
License: BSD-2-Clause License
Installers:
- Architecture: x64
  InstallerUrl: https://developers.yubico.com/yubioath-desktop/Releases/yubioath-desktop-5.0.5-win64.msi
  InstallerSha256: 580C825A5AF14989056144B90706E01070BF09F81EAABD0BE10BCEE2508EB2B9
  ProductCode: '{C4938DCC-540E-43DB-BDC2-962A94308617}'
  InstallerType: msi
  InstallerSwitches:
    Silent: /qn /norestart
    SilentWithProgress: /qn /norestart
- Architecture: x32
  InstallerUrl: https://developers.yubico.com/yubioath-desktop/Releases/yubioath-desktop-5.0.5b-win32.msi
  InstallerSha256: 789E873C9B96C5F10A315227BF23FD68B3EA62C517BD0A03A80F6DDB4413FA72
  ProductCode: '{E736B756-59E5-4F93-A6B3-9B83A3011AB2}'
  InstallerType: msi
  InstallerSwitches:
    Silent: /qn /norestart
    SilentWithProgress: /qn /norestart
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0